name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost.Beast
      run: |
        
        sudo apt-get update
        git clone --recursive https://github.com/boostorg/boost.git
        cd boost
        ./bootstrap.sh
    - run: echo “Hello”
