name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost.Beast
      run: |
        sudo add-apt-repository -y ppa:boost-latest/ppa
        sudo apt-get update
        sudo apt-get install -y libboost-dev

    - run: echo “Hello”
    
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
