name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-cache search boost-beast
    - name: Install Boost.Beast
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-beast-dev

    - run: echo “Hello”
    
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
